  

# 00. Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI


In [1]:
import torch # type: ignore
import numpy as  np # type: ignore
import pandas as pd # type: ignore
import matplotlib.pyplot as plt # type: ignore


## Introduction to  Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
#scalar

scalar = torch.tensor(7)
scalar
 

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensdor back as Python int
scalar.item()


7

In [6]:
# Vector 
vector = torch.tensor([7,7])
vector


1

In [7]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
#TENSOR

TENSOR = torch.tensor([[[1,3,5],[7,10,14],[13,43,53]]])
TENSOR

tensor([[[ 1,  3,  5],
         [ 7, 10, 14],
         [13, 43, 53]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[ 1,  3,  5],
        [ 7, 10, 14],
        [13, 43, 53]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> u pdata random numbers `

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [23]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4811, 0.4701, 0.4769, 0.4837],
        [0.1323, 0.1410, 0.8125, 0.9098],
        [0.7805, 0.9299, 0.9164, 0.3187]])

In [25]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height , width , colour channel
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [28]:
# Create a tensor of all zeros 
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

In [32]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [41]:
# Use torch.range()
one_to_ten = torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor dataypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:

1. Tensors not right dataype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [52]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what dataype is the tensor(e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Wheter or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [53]:
float_32_tensor.dtype

torch.float32

In [56]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [58]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [60]:
int_32_tensor = torch.tensor([3,6,9],dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [61]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right dataype - to do get dataype from a tensor ö can use `tensor.dtype` 
2. Tensors not right shape - to get shape from a tensor , can use `tensor.shape`
3. Tensors not on the right device  - to get device from a tensor , can use `tensor.device`

In [8]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor 

tensor([[0.8186, 0.6610, 0.4026, 0.8197],
        [0.6477, 0.1179, 0.5428, 0.1456],
        [0.5020, 0.0818, 0.1775, 0.2042]])

In [9]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor :{some_tensor.size()}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.8186, 0.6610, 0.4026, 0.8197],
        [0.6477, 0.1179, 0.5428, 0.1456],
        [0.5020, 0.0818, 0.1775, 0.2042]])
Datatype of tensor : torch.float32
Shape of tensor :torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [2]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [3]:
# Multiply tensor by 10
tensor=tensor * 10

In [4]:
# Substract 10
tensor - 10

tensor([ 0, 10, 20])

In [5]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([100, 200, 300])

In [6]:
torch.add(tensor,10)

tensor([20, 30, 40])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Elemnt-wise multiplication
2. Matrix multiplication (dot product)


More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will 
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)`
* `(3,2) @ (2,3)`


In [7]:
# Element wise multiplication 
print(tensor, "*" ,tensor)
print(f'Equals:{tensor * tensor}')

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals:tensor([100, 400, 900])


In [8]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(1400)

In [9]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3


14

In [14]:
tensor @ tensor

tensor(1400)

In [12]:
%%time
value = 0 
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
value

CPU times: total: 0 ns
Wall time: 1.04 ms


tensor(1400)

In [13]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(1400)

### One of the most common errors in deep learning: shape errors

In [9]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [6]:
tensor_B , tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

To fix our tensor shape issues , we can manipulate the shape of one of our tensors using **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [7]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [8]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes:tensor_A={tensor_A.shape} (same shape as above),tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes:tensor_A=torch.Size([3, 2]) (same shape as above),tensor_B.T=torch.Size([2, 3])
Multiplying:torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min,max,mean,sum , etc (tensor aggregation)

In [21]:
# Crete a tensor 
x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [12]:
# Fomd the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [13]:
# Find the max
torch.max(x), x.max()


(tensor(90), tensor(90))

In [16]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [17]:
# Find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding the positional min and  max

In [22]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [24]:
# Find the position in tensor that has the minimum value with argmin() -> return index position of target tensor where the minimum value occurs 
x.argmin()

tensor(0)

In [25]:
x[0]

tensor(1)

In [26]:
# Find the position in tensor that has the maximum value with argmax() -> return index postion of target tensor where the maximum value occurs
x.argmax()

tensor(9)

In [27]:
x[9]

tensor(91)

## Reshaping , stacking ,squeezing and unsqueezing tensors 

* Reshaping - reshapes an input tensor to a defined shape
* View- Returnn a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dımensıons from a tensor
* Unsqueeze * add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in certain way

In [2]:
# Let's create a tensor
x=torch.arange(1.,10.)

x,x.shape 

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [3]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
# Change the view
z= x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [5]:
# Changin z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [6]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [11]:
# torch.squeeze() -> removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extgra dimensions 
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [14]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x}")

# Add am extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [16]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height,width,colour_channels]

# Permute the original tensor to rearrange  the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shift axis 0->1 , 1->2 ,2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels,height,width]



Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [9]:
x_original=[0,0,0]= 728218
x_original[0,0,0], x_permuted[0,0,0] 

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy.

In [17]:
# Create a tensor
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [18]:
# Let's index on our new tensor
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
# Let's index on the middle bracket (dim=1)
x[0,0]

tensor([1, 2, 3])

In [21]:
# Let's index on the most inner bracket (last dimension)
x[0,0,0]

tensor(1)

In [24]:
# You can also use ":" to select "all" of a target dimension 
x[:, 0]

tensor([[1, 2, 3]])

In [29]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [30]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2 dimension
x[:, 1, 1]

tensor([5])

In [31]:
# Get index 0 of 0th and 1 dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [34]:
# Index on x to return 9
print(x[:,2,2])

#Index on x to return 3,6,9
print(x[:, :, 2])

tensor([9])
tensor([[3, 6, 9]])


## Pytorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()` 

In [38]:
# NumPy array to tensor

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy ->pytorch , pytorch reflects numpy's default dataype of float64 unless specified otherwise 
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [39]:
# Change the value of array, what will this do to `tensor`
array = array+1 
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [40]:
# Tensor to numpy array
tensor= torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [41]:
# Change the tensor , what happepns to `numpy_tensor`?
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
`starts with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again-> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed** 

Essentially what the  random seed does is "flavour" the randomness.

In [30]:
# Create two random tensorws 
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.1747, 0.4359, 0.2516, 0.0426],
        [0.6355, 0.6500, 0.6714, 0.2346],
        [0.3631, 0.4809, 0.4393, 0.5141]])
tensor([[0.6574, 0.1336, 0.9526, 0.0830],
        [0.0515, 0.6750, 0.8491, 0.6337],
        [0.2870, 0.0927, 0.5298, 0.2451]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [33]:
# Let's make some random but reproducible tensors 
# Set the random seed

RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resourrces for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Runing tensors and PyTorch objects on the GPUs (and making faster computations)


GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good.)

### 1. Getting a GPU

1. Easisest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU , there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 PyTorch + GPU drivers (CUDA) takes a littlle bit of setting up, to do this refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [3]:
!nvidia-smi

Sat Aug 31 13:15:53 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.81                 Driver Version: 560.81         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   54C    P8             10W /   85W |     216MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [4]:
#Check  for the GPU access with PyTorch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html


E.g. run on GPU if available, else default to CPU

In [6]:
# Setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
# Count number of devices 
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [9]:
# Crate a tensor (default on the CPU)

tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu 

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [11]:
# If tensor is on GPU, can't transfrorm it to NumPy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [13]:
tensor_on_gpu 

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum

See exercises for this notebook here:https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises 